<?php declare(strict_types=1);
/**
 * This file is part of morpho-os/framework
 * It is distributed under the 'Apache License Version 2.0' license.
 * See the https://github.com/njcom/framework/blob/main/LICENSE for the full license text.
 */
namespace Morpho\Compiler\Frontend;

use Morpho\Compiler\ILang;

// In formal language theory, a context-free language (CFL) is a language generated by a context-free grammar (CFG).
interface IContextFreeLang extends ILang {

}