<?php
/**
 * @var $body
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/localhost/rc/favicon.ico">
    <meta name="description" content="">
    <?php if (isset($this->pageTitle)) { ?>
        <title><?= $this->pageTitle ?></title>
    <?php } ?>
    <link rel="stylesheet" href="/node_modules/toastify-js/src/toastify.css">
    <link href="/localhost/lib/base/index.css" rel="stylesheet">
    <?php /*
    <link href="/localhost/rc/css/offcanvas.css" rel="stylesheet">
 */ ?>
</head>
<body id="<?= $this->pageHtmlId() ?>">
<?php require __DIR__ . '/_main-menu.phtml' ?>
<main class="container-fluid">
    <?php if (isset($this->pageTitle)) { ?>
        <h1 id="page-title"><?= $this->pageTitle ?></h1>
    <?php } ?>
    <?php print $this->messenger()->renderPageMessages(); ?>
    <?php print $body; ?>
</main>
<script src="/node_modules/imd/index.js"></script>
<script src="/node_modules/jquery/dist/jquery.js"></script>
<script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.js" data-amd="bootstrap"></script>
<script src="/node_modules/toastify-js/src/toastify.js"></script>
<script src="/localhost/lib/base/index.js"></script>
<script src="/localhost/lib/app/index.js"></script>
</body>
</html>