# https://github.com/srggrs/assign-one-project-github-action
on:
  workflow_dispatch:
  issues:
    types: [ opened, labeled ]
  pull_request:
    types: [ opened, labeled ]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Assign new issues to a project
    steps:
      - name: Assign NEW issues and NEW pull requests to a project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/orgs/njcom/projects/9'
          column_name: 'todo'
