on:
  schedule:
    # At 02:00 every day
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'module/parser: Pull changes for PEG'
        run: |
          make update-peg

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
