on:
  schedule:
    # At 02:00 every day
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - latest
    name: ${{ matrix.operating-system }}, php-${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: mbstring, xdebug, pcov, intl, gd
          #ini-values: "post_max_size=256M, short_open_tag=On, date.timezone=UTC"

      - name: 'Pull changes for PEG'
        run: |
          make update-peg

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
